# Generated by Django 5.2.5 on 2025-09-26 08:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report_image_report_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
