# Generated by Django 5.2.5 on 2025-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='reports/voice/'),
        ),
    ]
