# Generated by Django 5.2.5 on 2025-09-26 18:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_civic'),
    ]

    operations = [
        migrations.AddField(
            model_name='civic',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        # Step 1: make old CharField nullable at the DB level so we can set NULLs
        migrations.AlterField(
            model_name='civic',
            name='location',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        # Step 2: clear any existing non-geometry text by setting NULL
        migrations.RunSQL(sql="UPDATE api_civic SET location = NULL;", reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='civic',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
